###############
# conststants #
###############

DEFAULT_TARGET_GUIDANCE_SCALE = 15
DEFAULT_SOURCE_GUIDANCE_SCALE = 3.5
DEFAULT_DIFFUSION_STEPS = 100
DEFAULT_SKIP_STEPS = 36
DEFAULT_SEED = 0


DEFAULT_SEGA_CONCEPT_GUIDANCE_SCALE = 5
DEFAULT_WARMUP_STEPS = 1
DEFAULT_THRESHOLD = 0.95
DEFAULT_NEGATIVE_GUIDANCE=False